about_chat:
  label: "About Chat"
  use_answer: true
  answer_status: unanswerable_question_routing
  canned_responses:
    - "Sorry, I experienced a technical error while trying to answer your question. Please try again."

about_mps:
  label: "About MPs"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - Sorry, I cannot answer that question. You may be able to find your answer on [the UK Parliament website](https://www.parliament.uk/).<br /><br />If you have questions that can be answered using GOV.UK guidance, I'd be happy to help.

advice_opinions_predictions:
  label: "Advice, opinions, predictions"
  use_answer: true
  answer_status: unanswerable_question_routing
  canned_responses:
    - "Sorry, I experienced a technical error while trying to answer your question. Please try again."

character_fun:
  label: "Character fun"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - I can only provide information based on GOV.UK guidance, so I cannot answer that. If you have a different question, Iâ€™d be happy to help.

genuine_rag:
  label: "Genuine RAG"
  use_answer: false

gov_transparency:
  label: "Government transparency"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - Sorry, I cannot answer your question. You may be able to find the information by [searching on GOV.UK](https://www.gov.uk/).<br /><br />If not, check [Freedom of Information (FOI) responses](https://www.gov.uk/search/transparency-and-freedom-of-information-releases?content_store_document_type=foi_release) to find out if your question has already been answered. You can also [make your own FOI request](https://www.gov.uk/make-a-freedom-of-information-request).

greetings:
  label: "Greetings"
  use_answer: false
  answer_status: clarification
  canned_responses:
    - Hi ðŸ‘‹ How can I help you?
    - How can I help you today?
    - Hello. How can I assist you today?
    - What can I help you with today?
    - Hi. Ask me a question to get started.

harmful_vulgar_controversy:
  label: "Harmful, vulgar, controversy"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - I can only provide information based on GOV.UK guidance, so I cannot answer that. If you have a different question, Iâ€™d be happy to help.

multi_questions:
  label: "Multi-questions"
  use_answer: true
  answer_status: clarification
  canned_responses:
    - "Sorry, I experienced a technical error while trying to answer your question. Please try again."

negative_acknowledgement:
  label: "Negative acknowledgement"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - Iâ€™m sorry. You can try asking the question again. I can also answer other questions, if you have any.
    - Iâ€™m sorry. You can try rephrasing your question or ask something else.
    - Iâ€™m sorry. You could try rephrasing your question, or ask a different one.
    - Iâ€™m sorry. You could try asking the question again. Or you can ask a new question.
    - Iâ€™m sorry. Youâ€™re welcome to ask your question again or try asking something else.

non_english:
  label: "Non-English"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - I'm sorry, currently I can only respond in English, but I'm happy to help. Please feel free to ask again.

personal_info:
  label: "Personal information"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - I do not have access to any personal or confidential information. You can try searching for the [service you need on GOV.UK](https://www.gov.uk/search/services). Or ask me another question, if you need more help.

requires_account_data:
  label: "Requires account data"
  use_answer: true
  answer_status: unanswerable_question_routing
  canned_responses:
    - I do not have access to any personal or confidential information. You can try searching for the [service you need on GOV.UK](https://www.gov.uk/search/services). Or ask me another question, if you need more help.

positive_acknowledgement:
  label: "Positive acknowledgement"
  use_answer: false
  answer_status: unanswerable_question_routing
  canned_responses:
    - Iâ€™m happy to answer more questions, if you have any.
    - If thereâ€™s anything else youâ€™d like to ask, Iâ€™m happy to assist.
    - If youâ€™ve got more questions, Iâ€™m here to help.
    - If youâ€™ve got any follow-up questions or would like to ask about something else, Iâ€™m happy to keep chatting.
    - Feel free to ask me another question.

vague_acronym_grammar:
  label: "Vague, acronym, grammar"
  use_answer: true
  answer_status: clarification
  canned_responses:
    - "Sorry, I experienced a technical error while trying to answer your question. Please try again."

unclear_intent:
  label: "Unclear intent"
  use_answer: true
  answer_status: clarification
  canned_responses:
    - "Sorry, I experienced a technical error while trying to answer your question. Please try again."
