thresholds:
  retrieved_from_index: 80
  minimum_score: 0.75
  max_results: 20

_shared_document_types:
  corporate_information_types: &corporate_information_types
    about:
      weight: 1.1
    complaints_procedure:
      weight: 1.1
    modern_slavery_statement:
  publication_document_types: &publication_document_types
    form:
    guidance:
      weight: 1.1
    notice:
      weight: 0.5
    promotional:
    regulation:
    statutory_guidance:

document_types_by_schema:
  answer:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      answer:
        weight: 2.0

  corporate_information_page:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types: *corporate_information_types

  detailed_guide:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types:
      detailed_guide:
        weight: 1.5

  guide:
    parser: Chunking::ContentItemParsing::PartsContentParser
    document_types:
      guide:
        weight: 2.0

  help_page:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      help_page:
        weight: 1.5

  html_publication:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types:
      html_publication:
        requires_parent_document_type: *publication_document_types

  local_transaction:
    parser: Chunking::ContentItemParsing::TransactionParser
    document_types:
      local_transaction:

  manual:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      manual:

  place:
    parser: Chunking::ContentItemParsing::TransactionParser
    document_types:
      place:

  manual_section:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      manual_section:
        weight: 1.5

  publication:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types: *publication_document_types

  service_manual_guide:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types:
      service_manual_guide:
        weight: 0.5

  simple_smart_answer:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      simple_smart_answer:
        weight: 2.0

  specialist_document:
    parser: Chunking::ContentItemParsing::BodyContentArrayParser
    document_types:
      business_finance_support_scheme:
        weight: 2.0
      export_health_certificate:
        weight: 0.5
      hmrc_contact:
      international_development_fund:
      licence_transaction:
        weight: 2.0

  step_by_step_nav:
    parser: Chunking::ContentItemParsing::StepByStepNavParser
    document_types:
      step_by_step_nav:
        weight: 2.0

  take_part:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types:
      take_part:
        weight: 0.5

  transaction:
    parser: Chunking::ContentItemParsing::TransactionParser
    document_types:
      transaction:
        weight: 2.0

  travel_advice:
    parser: Chunking::ContentItemParsing::TravelGuideParser
    document_types:
      travel_advice:
        weight: 1.5

  worldwide_corporate_information_page:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types: *corporate_information_types

  worldwide_organisation:
    parser: Chunking::ContentItemParsing::BodyContentParser
    document_types:
      worldwide_organisation:
        weight: 1.1
